const UserActionTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_CONNECTED_USERS: 'SET_CONNECTED_USERS',
  SET_REGISTRATION_SOCKET: 'SET_REGISTRATION_SOCKET',
  SET_INVITED: 'SET_INVITED',
  TOGGLE_TURN: 'TOGGLE_TURN',
  SET_TURN: 'SET_TURN',
}

export default UserActionTypes;